MyFtp
YelenaZvyagina/HometasksCourse2 pull request #15
Opened 2022-04-14 07:38 UTC by YelenaZvyagina

2022-08-30 12:26 UTC, yurii-litvinov requested changes
В целом хорошо, но есть пара важных замечаний.

2022-08-30 12:26 UTC, yurii-litvinov commented on src/MyFtp/Client/Program.cs
> +    public static async Task Main(string[] args)
Лучше использовать top-level statements и этого просто не писать --- компилятор и так сгенерирует как раз то же самое

2022-08-30 12:26 UTC, yurii-litvinov commented on src/MyFtp/Client/Program.cs
> +        if (!int.TryParse(args[3], out var port))
Надо ещё проверять, что порт от 0 до 65535

2022-08-30 12:26 UTC, yurii-litvinov commented on src/MyFtp/Client/Program.cs
> +        switch (requestType)
```suggestion
        var client = new Client(ip, port);

        switch (requestType)
```

2022-08-30 12:26 UTC, yurii-litvinov commented on src/MyFtp/Client/Client.cs
> +    private readonly TcpClient _client = new();
Он IDisposable, следовательно и Client должен быть IDisposable ("диспозабельность заразна").

2022-08-30 12:26 UTC, yurii-litvinov commented on src/MyFtp/Client/Program.cs
> +                    Console.WriteLine("Operation was canceled");
Но, как я понимаю, никакого способа отменить операцию  у клиента нет :)

2022-08-30 12:26 UTC, yurii-litvinov commented on src/MyFtp/MyFtpTests/MyFtpTests.cs
> +namespace MyFtpTests;
namespace лучше писать в самом начале, более канонично

2022-08-30 12:26 UTC, yurii-litvinov commented on src/MyFtp/Server/Program.cs
> +        await server.RunServer();
Тут тоже нет никакого способа остановить сервер. Для клиента это ещё более-менее ок, но для сервера критично --- он по идее должен работать, пока его не остановят, так что если его никак не остановить, то не существует способа корректно закончить работу.

2022-08-30 12:26 UTC, yurii-litvinov commented on src/MyFtp/Server/Server.cs
> +            var tcpClient = await _server.AcceptTcpClientAsync();
А надо сюда тоже токен отмены передавать. Иначе мы будем вечно ждать нового подключения и не сможем завершиться.

2022-08-30 12:26 UTC, yurii-litvinov commented on src/MyFtp/Server/Server.cs
> +        await using var stream = client.GetStream();
Надо где-то сделать using на client, он ведь IDisposable

2022-09-09 08:35 UTC, yurii-litvinov requested changes

2022-09-09 08:35 UTC, yurii-litvinov commented on src/MyFtp/Client/Client.cs
> +    public Client(IPAddress ip, int port)
```suggestion
    private readonly int _port;

    public Client(IPAddress ip, int port)
```

2022-09-09 08:35 UTC, yurii-litvinov commented on src/MyFtp/Server/Program.cs
> +await server.RunServer();
Эм, что? :)

2022-09-19 21:29 UTC, Dalvikk approved these changes

2022-09-19 21:30 UTC, closed without merging